---

- hosts: all
  become: true
  tasks:
  - name: Update Repository index
    apt:
      update_cache: yes

  - name: install the apache2 package (this is a comment)
    apt:
      name: apache2
      state: latest
  
  - name: add php support for apache
    apt:
      name: libapache2-mod-php
      state: latest
