---

- hosts: all                        # target all hosts in inventory file
  become: true                      # run commands as superuser
  tasks:                            # run the following tasks
  # Ubuntu
  - name: Update Repository index
    apt:                            # use the 'apt' module
      update_cache: yes             # update the repo index
    when: ansible_distribution == "Ubuntu"    # target Ubuntu only here

  - name: install the apache2 package # this is a comment
    apt:
      name: apache2                 # name of package to install
      state: latest                 # update or install latest package
    when: ansible_distribution in ["Ubuntu", "Debian"] # target debian and ubuntu here
  
  - name: add php support for apache
    apt:
      name: libapache2-mod-php
      state: latest
    when: ansible_distribution == "Ubuntu"


  # Fedora
  - name: Update Repository index
    dnf:                            # use the 'apt' module
      update_cache: yes             # update the repo index
    when: ansible_distribution == "Fedora"    # target Ubuntu only here

  - name: install the apache2 package # this is a comment
    dnf:
      name: httpd                   # name of package to install
      state: latest                 # update or install latest package
    when: ansible_distribution in "Fedora" # target debian and ubuntu here
  
  - name: add php support for apache
    dnf:
      name: php
      state: latest
    when: ansible_distribution == "Fedora"
