---

- hosts: all
  become: true
  tasks:

  - name: remove the apache2 package (this is a comment)
    apt:
      name: apache2
      state: absent
  
  - name: remove php support for apache
    apt:
      name: libapache2-mod-php
      state: absent
