---

- hosts: all
  become: true
  pre_tasks:      # Use pre_tasks to force these first

  - name: install updates (Fedora)
    dnf:
      update_only: yes
      update_cache: yes
    when: ansible_distribution == "Fedora"

  - name: install updates (Ubuntu)
    apt:
      upgrade: yes       # preferred ubuntu syntax
      update_cache: yes
    when: ansible_distribution == "Ubuntu"
  
- hosts: web_servers   # target webserver from the inventory host group '[web_servers]'
  become: true
  tasks:

  - name: install the apache2 & php packages on ubuntu
    apt:
      name:
        - apache2
        - libapache2-mod-php
      state: latest
    when: ansible_distribution in ["Ubuntu", "Debian"]
  
  - name: install the apache2 and php packages on fedora 
    dnf:
      name:
        - httpd
        - php
      state: latest
    when: ansible_distribution in "Fedora"

- hosts: db_servers
  become: true
  tasks:
    - name: install mariadb package (Fedora)
      dnf:
        name: mariadb
        state: latest
      when: ansible_distribution == "Fedora"
    
    - name: install mariadb package (Ubuntu)
      dnf:
        name: mariadb-server
        state: latest
      when: ansible_distribution == "Ubuntu"

- hosts: file_servers
  become: true
  tasks:
  - name: install samba package (Same package name for all dists)
    package:
      name: samba
      state: latest
                    # no need for 'when' as samba package name same on all dists
