- name: install the apache2 & php packages on ubuntu
  tags: apache,apache2,ubuntu   # multiple tags like this
  apt:
    name:
      - apache2
      - libapache2-mod-php
    state: latest
  when: ansible_distribution in ["Ubuntu", "Debian"]

- name: install the apache2 and php packages on fedora
  tags: apache,httpd,fedora
  dnf:
    name:
      - httpd
      - php
    state: latest
  when: ansible_distribution in "Fedora"

- name: start httpd (Fedora only, ubuntu does this automatically)
  tags: apache,fedora,httpd
  service:
    name: httpd
    state: started
    enabled: yes
  when: ansible_distribution == "Fedora"

- name: copy default html file for site
  tags: apache,apache2,httpd
  copy:
    src: default_site.html          # file lives inside folder called 'files' but ansible doesn't need to ref it
    dest: /var/www/html/index.html
    owner: root
    group: root
    mode: 0644
